services:
  - type: web
    name: youtube-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    region: frankfurt  # or oregon/dublin depending on location